version: '3.8'
services:
  node-rest-api:
    container_name: node-rest-api
    build:
      context: .
      dockerfile: Dockerfile.node
    entrypoint: sh -c 'yarn install --frozen-lockfile && yarn start:dev'
    environment:
      NGINX_PORT: ${NGINX_PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - node-rest-net

  node-rest-nginx:
    container_name: node-rest-nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    expose:
      - ${NGINX_PORT}
    networks:
      - node-rest-net
    links:
      - node-rest-api

networks:
  node-rest-net:
